name: beauty
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexagon: ^0.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: LavishlyYours
      fonts:
        - asset: assets/fonts/LavishlyYours-Regular.ttf
          weight: 400
          style: italic
    - family: Splash
      fonts:
        - asset: assets/fonts/Splash-Regular.ttf
          weight: 400
    - family: BilboSwashCaps
      fonts:
        - asset: assets/fonts/BilboSwashCaps-Regular.ttf
          weight: 400
          style: italic
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
          weight: 400
